### ISSUE TITLE
Stemcell writeup has incorrect statement?

### ISSUE THREAD

**Issue by pivotal-sukhil-suresh** [cloudfoundry/docs-bosh#130]
http://bosh.io/docs/stemcell.html

Is this correct?

_"In addition to being generic, stemcells for one OS (e.g. all Ubuntu Trusty stemcells) are exactly the same for all infrastructures. This property of stemcells allows BOSH users to quickly and reliably switch between different infrastructures without worrying about the differences between OS images."_

_"Reusing base Operating System images across different IaaS"_

Doesn't bosh.io have different downloads of a stemcell based on the IAAS ?

**Comment by dpb587-pivotal** [comment]
Kind of conflated terms - "stemcell" here should refer to "stemcell base image" or something. Base image (aka "OS image") is shared across infrastructures and is what the comment refers to. In documentation, "stemcell" typically refers to an (IaaS+OS+bosh-version)-specific combination.

Might be nice if the docs could be clarified though - it does sound confusing and sort of implies you could upload a given stemcell to any IaaS.

**Comment by cppforlife** [comment]
packaging part is different (last step more or less), but for all other purposes they could be considered the same. we are moving towards stecells being shipped by format instead of by iaas. for example: vsphere stemcell can be used without a problem on vcloud. rackhd and openstack also share the stemcell.

i dont want to mention info about dev's "os image" since thats a very specific optimization bosh devs perform and is invisible (as it should be) to consumers of stemcells.

**Comment by pivotal-sukhil-suresh** [comment]
Thanks for clarifying Dmitry & Danny! The issue was raised only because (as of now), from the user perspective, the Stemcell tarball to download (from bosh.io) for an OS differs based on the IAAS. And this experience kind of contradicts the statement - _"stemcells for one OS (e.g. all Ubuntu Trusty stemcells) are exactly the same for all infrastructures"_ 

The clarifications given makes it clear that this is only a packaging difference... and glad that, the statements will hold (more) true in the future when we move away from IAAS based packaging.
