### ISSUE TITLE
AWS logs EIP unnecessary

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/docs-bosh#314]
The elastic IP required by the AWS docs (https://github.com/cloudfoundry/docs-bosh/blob/master/init-aws.html.md.erb) seem to be superfluous; is that correct?

**Comment by jadekler** [comment]
Ah, this appears to be necessary - the docs need to specify that the EIP needs to be associated to the bosh vm.

**Comment by dpb587-pivotal** [comment]
Good find. For the default steps documented for `bosh create-env ...`, the Elastic IP is not required (since we recommend director be internally-accessible only). However, if you [add an external IP](https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml), you'd need to create the EIP.

I'll see if we can clarify the documentation a bit more around this.
