### ISSUE TITLE
Would like to use `disk_cids` in the CPI method "create_vm"

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/docs-bosh#571]
https://www.bosh.io/docs/cpi-api-v1-method/create-vm/ mentions:
```
disk_cids [Array of strings] Array of disk cloud IDs for each disk that created VM will most likely be attached; they could be used to optimize VM placement so that disks are located nearby.
```

1. `most likely` means that the disk might not be attached to the VM in some situation. Could you please describe the situation?
2. My understanding: when updating the VM with persistent disks, BOSH will detach the persistent disk, delete the old VM, create a new VM and attach the persistent disk. Then the `disk_cids` **MUST** be [an array of the persistent disk CIDs](https://github.com/cloudfoundry/bosh/blob/83b1650f88323f5f35ed2bca3059d2bc27642f36/src/bosh-director/lib/bosh/director/vm_creator.rb#L24), which were attached in the old VM. Could you please confirm it?
3. If the item 2 is correct, then CPI can use the `disk_cids` to do some optimization or validation. Example:
    1. Check whether `instance_type` and the disk can work together. In Azure, some instance types support [premium storage](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage), some don't. CPI can fail fast if the specified instance type doesn't support the disk type.
    1. Attach the disk when creating VMs. Then CPI does nothing in `attach_disk`. It may reduce deployment time.

It would be very nice if the item 1 and 2 is documented. CC: @mfine30 @jfmyers9 @dpb587-pivotal

**Comment by dpb587-pivotal** [comment]
> 1. most likely means that the disk might not be attached to the VM in some situation. Could you please describe the situation?

It will be empty in the case where a disk has not yet been created for new instances. For the specific case of when a disk passed to `create_vm` may not be used... it could happen in the case where someone runs `cancel-task` on a deployment which started running `create_vm`, but did not successfully finish nor get to the point of attaching disks. Future deploys after that failed deploy may then want to create new VMs and eventually attach the hinted disk.

> 2. ... Could you please confirm it?

Currently, that looks to be the case. However, keep in mind we intend these as hints; not guarantees. The subsequent `attach_disk` calls should still work with changed CIDs, although if there is an IaaS incompatibility, the CPI may still error in the call.

> 3. optimizations/validations

Azure's use case with the instance type and premium storage matrix does make sense to have some validation (which I think the Azure API already provides). However, if you want additional, nicer user errors around this... you should always do this in, at least, the `attach_disk` stage (because that call can happen regardless of `create_vm`).

Regarding `create_vm` pre-attaching disks... you should avoid this. This causes the state of the IaaS resources to become different than BOSH expects. This can cause internal issues later if the BOSH resurrector attempts resurrecting a partially failed deploy, or if the user is trying to verify the state of their deployments with `cck`.

Also, these are disk hints... so in theory, director may follow up the `create_vm` with an `attach_disk` call with a different CID. To account for this, your `attach_disk` would need to introduce its own state management to detect if there is already a disk attached, and if it was "intentional" from BOSH's perspective. Having two separate systems managing this would likely introduce bugs somewhere along the way.

While those optimizations may save a few moments in the `create_vm`+`attach_disk` scenarios, the additional complexities it introduces is probably not worth it without extensive edge case testing on your side.

Hopefully this helps answer your questions? But happy to discuss further.

@dpb587-pivotal && @belinda-liu

**Comment by bingosummer** [comment]
Thanks @dpb587-pivotal && @belinda-liu for giving us so many helpful guidance.

> validations

There's a problem about the instance type and premium storage. For example, 
1. The instance_type `Standard_DS1_v2` supports premium storage. By default, CPI will attach a premium persistent disk to it.
2. When the instance_type is changed to `Standard_D1_v2`, which doesn't support Premium storage. The old VM is deleted, and the original premium persistent disk should be attached to the new created VM. But it can't.

Short goals:
The instance type can be changed by `vm_type` or `vm_resources`. Using `disk_cid`, we can do the validations in `create_vm` for two scenarios. For `vm_type` changing, CPI need to fail fast and ask users to change instance type. For `vm_resources` changing, CPI needs to calculate a premium-storage-supported instance type if the disk is a premium one.

Long goals:
* It would be very nice to make `disk_cids` guarantees.
* We are also thinking about a proposal to add a new CPI method called `validate_cloud_properties_changes?`. Director can call it to validate whether cloud properties change (e.g. instance type change) is good or bad, before it really create a VM.

> optimizations

I agree with you. We should avoid `create-vm` pre-attaching disks.

**Comment by jfmyers9** [comment]
Hi @bingosummer,

We don't think it is likely that we will make the `disk_cids` on `create_vm` a guarantee any time soon. It seems cleaner that the `disk_cids` specified in `attach_disk` do not necessarily need to be included in this list. This separation will enable us flexibility when implementing advanced lifecycles in the future (i.e. attaching new disks without recreating the instance).

With regards to `validate_cloud_properties_changes?`, we aren't sure that other IAAS's would benefit from this interface change. This would be a concern for us going forward if we were to add this to the generic CPI interface. We would definitely like to hear more about the proposal and how it might be used generically to benefit all CPIs.

As to the original questions, it would be difficult for us to document situation in which `the disk might not be attached to the VM in some situation` as this is very IAAS specific.

We are going to close this issue. Please feel free to reopen it if you have any further questions.

Best,

@jfmyers9 && @jrussett, CF BOSH
