### ISSUE TITLE
Document 'consumes' and 'provides' configuration in 'addons block'

### ISSUE THREAD

**Issue by KaiHofstetter** [cloudfoundry/docs-bosh#629]
The ['addons block'](https://bosh.io/docs/runtime-config/#addons) documentation does not mention the `consumes` and `provides` configurations, even though you can use it.
I think it make sense to reuse the description from the ['instance groups'](https://bosh.io/docs/manifest-v2/#instance-groups) documentation.

**Comment by h4xnoodle** [comment]
While you can use the bosh links `consumes` and `provides`, with addons links get tricky. Since an addon is on every VM by default (considering `include` and `exclude` rules), link resolution usually results in ambiguity. That is, because addon X is on every VM, every VM is now providing the link from X. Consumers of the link for X are unsure which instance to obtain the data from.

It's generally difficult to have an addon `provide` a link and then have that resolve properly, which is why I think the documentation is not present. If we did add documentation for it, there would be a huge caveat of "you must ensure this provider is only associated with one instance" which makes the feature pretty difficult to use in this case.
